# **Importing Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

* ### Checking Dataset Location

#  **Importing Dataset**

In [2]:
dataset = pd.read_csv('/kaggle/input/dummy-advertising-and-sales-data/Dummy Data HSS.csv')
print(dataset)

        TV      Radio  Social Media Influencer       Sales
0     16.0   6.566231      2.907983       Mega   54.732757
1     13.0   9.237765      2.409567       Mega   46.677897
2     41.0  15.886446      2.913410       Mega  150.177829
3     83.0  30.020028      6.922304       Mega  298.246340
4     15.0   8.437408      1.405998      Micro   56.594181
...    ...        ...           ...        ...         ...
4567  26.0   4.472360      0.717090      Micro   94.685866
4568  71.0  20.610685      6.545573       Nano  249.101915
4569  44.0  19.800072      5.096192      Micro  163.631457
4570  71.0  17.534640      1.940873      Macro  253.610411
4571  42.0  15.966688      5.046548      Micro  148.202414

[4572 rows x 5 columns]


# **Missing Data for dependent variable**

In [3]:
dataset['Sales'] = dataset['Sales'].fillna(dataset['Sales'].median())

In [4]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(y)

[ 54.73275715  46.67789698 150.1778288  ... 163.6314574  253.6104113
 148.2024141 ]


# **Encoding Categorical Data**

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [7]:
print(x)

[[0.0 1.0 0.0 ... 16.0 6.566230788 2.907982773]
 [0.0 1.0 0.0 ... 13.0 9.237764567 2.409567204]
 [0.0 1.0 0.0 ... 41.0 15.88644602 2.913410175]
 ...
 [0.0 0.0 1.0 ... 44.0 19.80007236 5.096191875]
 [1.0 0.0 0.0 ... 71.0 17.5346403 1.94087322]
 [0.0 0.0 1.0 ... 42.0 15.96668752 5.046547629]]


# **Missing Data for Dependent Variables**

In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 0:])
x[:, 0:] = imputer.transform(x[:, 0:])

In [9]:
print(x[11:, :])

[[0.0 1.0 0.0 ... 42.0 15.8073374 3.194924641]
 [0.0 0.0 1.0 ... 64.0 20.24042393 3.921147972]
 [0.0 1.0 0.0 ... 54.06685664182376 22.35166709 3.031815334]
 ...
 [0.0 0.0 1.0 ... 44.0 19.80007236 5.096191875]
 [1.0 0.0 0.0 ... 71.0 17.5346403 1.94087322]
 [0.0 0.0 1.0 ... 42.0 15.96668752 5.046547629]]


# **Splitting Dataset into Testing and Training**

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[160.61 157.66]
 [264.17 264.59]
 [299.44 298.88]
 ...
 [277.04 277.46]
 [100.21 103.42]
 [200.16 201.98]]


# **Visualizing Results**

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.994682178876875